### PR TITLE
initial hooks example page

### PR DESCRIPTION
**Pull request by campbieil**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Introduction - please don't put any inline links in the intro copy. If you want to send users elsewhere (is it really needed here?) please provide a descriptive link below the introduction (e.g. to find out more about hooks... etc)

**Comment by ghost** [comment]
@campbieil please correct the intro copy

**Review by campbieil — COMMENTED** [review]
beautiful 
Hey Magda?

**Review by ghost — APPROVED** [review]
lgtm

**Pull request merged**
