### PR TITLE
Add snapcraft, devices and community url patterns

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Add snapcraft, devices and community url patterns
Add folders and index templates for snapcraft and devices

## QA

- Follow the instructions in README.md to get started
- Go to http://localhost:8015/devices,  http://localhost:8015/snapcraft and http://localhost:8015/community to make sure they resolve

### CODE REVIEW

**Comment by grahambancroft** [comment]
[Add snapcraft, devices and community url patterns](https://trello.com/c/na8bfhxd/3170-add-snapcraft-devices-and-community-url-patterns)

**Review by anthonydillon — COMMENTED** [review]
Code and QA :+1:

**Review by anthonydillon — APPROVED** [review]

**Comment by anthonydillon** [comment]
Looks like a python lint error: 
```
webapp/templatetags.py:2:1: F401 'datetime.datetime' imported but unused
```

**Comment by WillMoggridge** [comment]
Yeah, seems outstanding and not created by this PR. I'll fix it shortly in a separate PR

**Pull request merged**
