### PR TITLE
Add sass-linting

### PR DESCRIPTION
**Pull request by WillMoggridge**
This is a continuation of #207 

The commits are a little unwieldly and I will happily flatten them a bit once I have confirmation for this PR.

QA
---

See the travis test.

Run the site, check everything looks reasonable.

### CODE REVIEW

**Comment by WillMoggridge** [comment]
[Setup sass linting](https://trello.com/c/nVrdvviC/2502-setup-sass-linting)

**Comment by WillMoggridge** [comment]
Linkchecker seems to have failed but I have not touched any links. Rerunning just in case.

**Comment by WillMoggridge** [comment]
Linkchecker fix has been proposed in PR #220 and this can be rebased once that is merged.

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code issues: 
- Use `$color-x-light;` instead of `#fff` please.
- Can you make #ebebeb use a variable please.

**Review by anthonydillon — APPROVED** [review]

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Pull request merged**
