### PR TITLE
Revive mir snaps guide

### PR DESCRIPTION
**Pull request by caldav**
## DONE
* Ported to Markdown
* A lot of cleanup
* Found its place in the nav
* Redirect from old URL

### CODE REVIEW

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
There are a couple of "workarounds" using --devmode for core regressions that are obsolete and can be dropped.

**Comment by Saviq** [comment]
Is there anything more you need from us to complete this?

**Comment by caldav** [comment]
All good, I've just spent some time testing the various stages.

**Comment by Saviq** [comment]
Seems good!

**Review by AlanGriffiths — APPROVED** [review]
LGTM

**Pull request merged**
