### PR TITLE
Add get started steps for cm3

### PR DESCRIPTION
**Pull request by caldav**
- New board page: Compute Module 3

@kubiko, please review the required hardware and flashing steps :)

### CODE REVIEW

**Comment by caldav** [comment]
Feedback has been provided on IRC. It's a +1 with the latest changes.

**Comment by caldav** [comment]
Merge pending on the CM3 Ubuntu Core image getting a stable release. Feel free to review but don't merge yet.

**Comment by caldav** [comment]
The stable image is now available, and this should be deployed today

**Review by anthonydillon — APPROVED** [review]
Code and QA :+1:

**Pull request merged**
