### PR TITLE
Renovate config: Use django 1.x

### PR DESCRIPTION
**Pull request by nottrobin**
Tell Renovate not to upgrade to Django 2 - it's not worth it for
this site, which will be decommissioned before too long.

### CODE REVIEW

**Comment by nottrobin** [comment]
@rarkins weren't you saying Renovate should have run a check on this PR, as it has "Renovate" in the title? Or did I misunderstand?

**Comment by nottrobin** [comment]
@rarkins ah yes that makes sense. A PR comment would be great - or it doesn't need to be a comment - just any way for me to validate the config would be fine.

I still can't get `renovate-config-validator` to work. I'm running it from within the root of this branch of this project:

``` bash
robin@xps:~/git/developer.ubuntu.com (renovate-keep-django-1)$ renovate-config-validator
Validating renovate.json
 INFO: Throwing preset error
renovate.json is not valid JSON
robin@xps:~/git/developer.ubuntu.com (renovate-keep-django-1)$ ls -l
total 1084
-rw-r--r--   1 robin robin 761856 Jan 30 07:58 cache.sqlite
-rw-r--r--   1 robin robin    432 Oct 10 14:57 Dockerfile
-rwxr-xr-x   1 robin robin    302 Oct 10 14:57 entrypoint
-rw-r--r--   1 robin robin   7651 Aug  9 09:46 LICENSE.txt
-rwxr-xr-x   1 robin robin    250 Aug  9 09:46 manage.py
drwxr-xr-x 512 robin robin  20480 Jan 29 16:08 node_modules
-rw-r--r--   1 robin robin   1012 Jan 30 09:22 package.json
-rw-r--r--   1 robin robin    962 Jan 29 13:54 README.md
-rw-r--r--   1 robin robin    877 Jan 29 15:57 redirects.yaml
-rw-r--r--   1 robin robin    552 Jan 30 09:22 renovate.json
-rw-r--r--   1 robin robin    566 Jan 30 09:22 requirements.txt
-rwxr-xr-x   1 robin robin  20043 Jan 29 13:54 run
drwxr-xr-x   7 robin robin   4096 Jan 30 09:22 static
drwxr-xr-x   5 robin robin   4096 Aug  9 09:46 templates
drwxr-xr-x   4 robin robin   4096 Jan 29 15:57 webapp
-rw-r--r--   1 robin robin 117662 Jan 25 22:40 yarn-error.log
-rw-r--r--   1 robin robin 129842 Jan 30 09:22 yarn.lock
robin@xps:~/git/developer.ubuntu.com (renovate-keep-django-1)$ cat renovate.json
{
  "extends": [
    "config:base",
    "schedule:weekends"
  ],
  "packageRules": [
    {
      "managers": ["pip"],
      "packageNames": ["markdown"],
      "allowedVersions": "<3"
    },
    {
      "managers": ["pip"],
      "packageNames": ["django"],
      "allowedVersions": "<2"
    },
    {
      "depTypeList": ["devDependencies"],
      "extends": [":automergeMinor"]
    },
    {
      "packagePatterns": ["*"],
      "minor": {
        "groupName": "all non-major dependencies",
        "groupSlug": "all-minor-patch"
      }
    }
  ]
}
$ sudo npm list -g | grep renovate
├─┬ renovate@14.3.25
│ ├─┬ @renovate/pep440@0.4.1
│ ├─┬ @renovatebot/docker-registry-client@3.3.0
```

**Comment by nottrobin** [comment]
@rarkins Thanks as always for your amazing help and swift replies, sorry for taking up so much of your time.

I did a bit more investigation and I've filed a bug report with a more specific description of the problem:
https://github.com/renovatebot/renovate/issues/3134

**Review by hatched — APPROVED** [review]
Thanks @nottrobin

**Pull request merged**
