### PR TITLE
Add sass-linting to automated tests

### PR DESCRIPTION
**Pull request by nottrobin**
Travis CI tests will now lint the sass as well, and fail on any errors.

I also fixed a ton of errors and warnings in the existing sass.

QA
---

See the travis test.

Run the site, check everything looks reasonable.

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code looks good but the navigation have regressions.

**Comment by anthonydillon** [comment]
intel joule developer

**Comment by anthonydillon** [comment]
@nottrobin would you mind taking a look at this one when you get a sec.

**Comment by anthonydillon** [comment]
@nottrobin can you return to this one when you get a sec.

**Comment by WillMoggridge** [comment]
I will continue this on with #219

**Pull request closed without merging**
