### PR TITLE
Update site to Vanilla 1.6.5

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
# Done

- Updated site to Vanilla 1.6.5, which includes:
  - Header and sidebar navigation
  - Base templates
  - Card templates
  - Grid templates
- Refactored scss files and minimised bespoke styling as much as possible

# QA
- Pull code and run `./run`
- Navigate to http://0.0.0.0:8015/
- Compare with https://developer.ubuntu.com/ and check everything looks/runs okay (especially the nav) and it's all Vanilla-fied

# Issues
- Fixes vanilla-framework/vanilla-framework#1466

### CODE REVIEW

**Review by caldav — CHANGES_REQUESTED** [review]
The search field at the top of http://developer.ubuntu.com-pr-344.run.demo.haus/target-platforms/boards is gone.

**Review by caldav — APPROVED** [review]
The boards page is clearly in need of a design change, but that works for now, thanks!

**Comment by kwm14** [comment]
## Visual review
There were a few pages to review but looking good @Caleb-Ellis only one design update 😄 
- [x] update .p-footer to `col-11` so it matches current site

**Comment by kwm14** [comment]
@Caleb-Ellis 👍

**Pull request merged**
